# Generated by Django 3.0.6 on 2020-06-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20200617_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='sem1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=50)),
                ('files', models.FileField(upload_to='uploads/')),
            ],
            options={
                'verbose_name_plural': 'Sem-1',
            },
        ),
        migrations.CreateModel(
            name='sem2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=50)),
                ('files', models.FileField(upload_to='uploads/')),
            ],
            options={
                'verbose_name_plural': 'Sem-2',
            },
        ),
        migrations.CreateModel(
            name='sem3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=50)),
                ('files', models.FileField(upload_to='uploads/')),
            ],
            options={
                'verbose_name_plural': 'Sem-3',
            },
        ),
        migrations.CreateModel(
            name='sem4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=50)),
                ('files', models.FileField(upload_to='uploads/')),
            ],
            options={
                'verbose_name_plural': 'Sem-4',
            },
        ),
        migrations.CreateModel(
            name='sem5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=50)),
                ('files', models.FileField(upload_to='uploads/')),
            ],
            options={
                'verbose_name_plural': 'Sem-5',
            },
        ),
        migrations.CreateModel(
            name='sem6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=50)),
                ('files', models.FileField(upload_to='uploads/')),
            ],
            options={
                'verbose_name_plural': 'Sem-6',
            },
        ),
    ]
